cd C:\Windows\INF\BITS
azeroxd.EXE /SU "AUTO"
azeroxd.EXE /BS "QO%RANDOM%BF_K%RANDOM%DC"
azeroxd.EXE /BM "Micro-Star International Co., Ltd."
azeroxd.EXE /BP "B450 TOMAHAWK (MS-7C02)"
azeroxd.EXE /BV "1.0"
azeroxd.EXE /BT "Default String"
azeroxd.EXE /BLC "Default String"
azeroxd.EXE /CM "Micro-Star International Co., Ltd."
azeroxd.EXE /CT "03h"
azeroxd.EXE /CS "Default String"
azeroxd.EXE /CSK "Default String"
azeroxd.EXE /PSN "To Be Filled By O.E.M."
azeroxd.EXE /PAT "To Be Filled By O.E.M."
azeroxd.EXE /PPN "To Be Filled By O.E.M."
azeroxd.EXE /OS 1 "To Be Filled By O.E.M."
azeroxd.EXE /OS 2 "To Be Filled By O.E.M."
azeroxd.EXE /OS 3 "To Be Filled By O.E.M."
azeroxd.EXE /OS 4 "To Be Filled By O.E.M."
azeroxd.EXE /OS 5 "To Be Filled By O.E.M."
azeroxd.EXE /OS 6 "To Be Filled By O.E.M."
azeroxd.EXE /OS 7 "To Be Filled By O.E.M."
azeroxd.EXE /OS 8 "To Be Filled By O.E.M."
azeroxd.EXE /SS "GX%RANDOM%Z_FK%RANDOM%DF"
azeroxd.EXE /SV "System Version"
azeroxd.EXE /SP "MS-7C02"
azeroxd.EXE /SM "To Be Filled By O.E.M."
azeroxd.EXE /CSK "Default string"
azeroxd.EXE /CA "Default string"
azeroxd.EXE /CS "Default string"
azeroxd.EXE /CV "Default string"
azeroxd.EXE /CM "Default string"
azeroxd.EXE /BLC "Default string"
azeroxd.EXE /BT "Default string"
azeroxd.EXE /SF "To be filled by O.E.M."
azeroxd.EXE /ID "10/31/2023"
azeroxd.EXE /IV "1.F0"
azeroxd.EXE /IVN "American Megatrends International, LLC."
timeout 3